/** Desired capabilities */
def capabilities = [
  browserName: 'Firefox',
  version: '57.0',
  platform: 'Windows 10'
]

pipeline {
  agent {
    dockerfile true
  }
  libraries {
    lib('fxtest@1.9')
  }
  options {
    ansiColor('xterm')
    timestamps()
    timeout(time: 1, unit: 'HOURS')
  }
  environment {
    PYTEST_PROCESSES = "${PYTEST_PROCESSES ?: "auto"}"
    PYTEST_ADDOPTS =
      "-n=${PYTEST_PROCESSES} " +
      "--tb=short " +
      "--color=yes " +
      "--driver=SauceLabs " +
      "--variables=capabilities.json"
    PULSE = credentials('PULSE')
    SAUCELABS = credentials('SAUCELABS')
  }
  stages {
    stage('Test') {
      steps {
        writeCapabilities(capabilities, 'tests/jenkins/capabilities.json')
        sh "pytest --junit-xml=tests/jenkins/results/py27.xml " +
        "--html=tests/jenkins/results/py27.html " +
        "--self-contained-html " +
        "--log-raw=tests/jenkins/results/py27_raw.txt " +
        "--log-tbpl=tests/jenkins/results/py27_tbpl.txt"
      }
      post {
        always {
          archiveArtifacts 'tests/jenkins/results/*'
          junit 'tests/jenkins/results/*.xml'
          submitToActiveData('tests/jenkins/results/py27_raw.txt')
          submitToTreeherder('treeherder', 'e2e', 'End-to-end integration tests', 'tests/jenkins/results/*', 'tests/jenkins/results/py27_tbpl.txt')
          publishHTML(target: [
            allowMissing: false,
            alwaysLinkToLastBuild: true,
            keepAll: true,
            reportDir: 'tests/jenkins/results',
            reportFiles: "py27.html",
            reportName: 'HTML Report'])
        }
      }
    }
  }
  post {
    failure {
      emailext(
        attachLog: true,
        attachmentsPattern: 'tests/jenkins/results/py27.html',
        body: '$BUILD_URL\n\n$FAILED_TESTS',
        replyTo: '$DEFAULT_REPLYTO',
        subject: '$DEFAULT_SUBJECT',
        to: '$DEFAULT_RECIPIENTS')
    }
    changed {
      ircNotification()
    }
  }
}
